### PR TITLE
bugfix/KBDEV-1254 New Records of Abstract Classes Unnecessarily Required Admin Permission

### PR DESCRIPTION
**Pull request by bnguyen-bcgsc**
- Fix bug in main view where new records of abstract classes (e.g.: ontology, relationship) required admin permission
- Fix rowData typos for ag grid calls
- Code lint

### CODE REVIEW

**Comment by mathieulemieux** [comment]
I don't understand why we need a client code change while ticket describes a very recent behavior. Any idea @bnguyen-bcgsc or @elewis2 ?

**Comment by bnguyen-bcgsc** [comment]
> I don't understand why we need a client code change while ticket describes a very recent behavior. Any idea @bnguyen-bcgsc or @elewis2 ?

@mathieulemieux we suspect that it worked initially because they had not hard-refresh the client when the new version was released and the change was made using 4.2.3. After examining the behaviour and recreating the issue, line 110 of MainView was determined to be the cause of the problem

**Comment by mathieulemieux** [comment]
@bnguyen-bcgsc, was the issue reported on prod? because last update was more than 2y ago...

**Comment by mathieulemieux** [comment]
Maybe the deployed version was still 4.2.3 though... I think we documented that issue before, so if it's the case, then it's start to make sense.

**Review by mathieulemieux — APPROVED** [review]

**Comment by bnguyen-bcgsc** [comment]
> @bnguyen-bcgsc, was the issue reported on prod? because last update was more than 2y ago...

I don't believe so since the change that caused the issue was added in just 6 months ago

**Review by kttkjl — APPROVED** [review]

**Review by elewis2 — APPROVED** [review]

**Pull request merged**
